[package]
name = "noah_trust"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/noah_trust.rs"
doctest = false

[dependencies]
anyhow.workspace = true
base64.workspace = true
chrono.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sha2.workspace = true
unicode-normalization = "0.1"

[dev-dependencies]
tempfile.workspace = true
