// The names phishing pages imitate, with the domains that really belong to
// them. A page whose host looks like one of these names but is not one of
// these domains gets the interstitial. Kept to brands whose logins are worth
// stealing; a longer list would mostly add false alarms.
"use strict";
(() => {
const Shield = (globalThis.Shield = globalThis.Shield || {});

Shield.BRANDS = [
  { name: "paypal", domains: ["paypal.com", "paypal.me", "paypalobjects.com"] },
  { name: "amazon", domains: ["amazon.com", "amazon.co.uk", "amazon.de", "amazon.ca", "amazon.fr", "amazon.it", "amazon.es", "amazon.co.jp", "amazon.com.au", "amazon.in", "amazon.com.mx", "amazon.nl", "amazon.se", "amazon.pl", "amazon.com.br", "amazon.sg", "amazon.ae", "amazon.sa", "amazon.eg", "amazon.com.tr", "amazon.cn", "amazon.jobs", "amazonaws.com", "aws.amazon.com", "amazon.dev", "primevideo.com", "audible.com"] },
  { name: "apple", domains: ["apple.com", "icloud.com", "apple.co", "me.com", "mac.com"] },
  { name: "icloud", domains: ["icloud.com", "apple.com"] },
  { name: "google", domains: ["google.com", "google.co.uk", "google.de", "google.fr", "google.ca", "google.com.au", "google.co.in", "google.co.jp", "google.es", "google.it", "google.nl", "google.com.br", "google.com.mx", "googleapis.com", "gstatic.com", "youtube.com", "gmail.com", "googleusercontent.com", "google.dev", "withgoogle.com", "goo.gl", "g.co", "blog.google", "about.google"] },
  { name: "gmail", domains: ["gmail.com", "google.com", "mail.google.com"] },
  { name: "microsoft", domains: ["microsoft.com", "live.com", "outlook.com", "office.com", "microsoftonline.com", "office365.com", "azure.com", "windows.com", "msn.com", "bing.com", "xbox.com", "skype.com", "microsoft.net", "sharepoint.com", "onedrive.com", "hotmail.com", "visualstudio.com", "azurewebsites.net", "microsoftonline-p.com", "msftauth.net", "aka.ms"] },
  { name: "outlook", domains: ["outlook.com", "live.com", "office.com", "microsoft.com"] },
  { name: "office", domains: ["office.com", "office365.com", "microsoft.com", "live.com", "microsoftonline.com"] },
  { name: "netflix", domains: ["netflix.com", "nflxext.com", "nflximg.net", "nflxvideo.net"] },
  { name: "facebook", domains: ["facebook.com", "fb.com", "fb.me", "fbcdn.net", "messenger.com", "meta.com", "facebook.net"] },
  { name: "instagram", domains: ["instagram.com", "cdninstagram.com", "ig.me"] },
  { name: "whatsapp", domains: ["whatsapp.com", "whatsapp.net", "wa.me"] },
  { name: "twitter", domains: ["twitter.com", "x.com", "t.co", "twimg.com"] },
  { name: "linkedin", domains: ["linkedin.com", "licdn.com", "lnkd.in"] },
  { name: "chase", domains: ["chase.com", "jpmorgan.com", "jpmorganchase.com", "jpmchase.com"] },
  { name: "wellsfargo", domains: ["wellsfargo.com", "wf.com", "wellsfargoadvisors.com"] },
  { name: "bankofamerica", domains: ["bankofamerica.com", "bofa.com", "merrilledge.com", "ml.com"] },
  { name: "citibank", domains: ["citi.com", "citibank.com", "citibankonline.com", "citicards.com"] },
  { name: "capitalone", domains: ["capitalone.com", "capitalone.ca", "capitalone.co.uk"] },
  { name: "americanexpress", domains: ["americanexpress.com", "amex.com", "aexp.com"] },
  { name: "barclays", domains: ["barclays.co.uk", "barclays.com", "barclaycard.co.uk", "barclaycardus.com"] },
  { name: "hsbc", domains: ["hsbc.com", "hsbc.co.uk", "us.hsbc.com", "hsbc.com.hk", "hsbc.ca"] },
  { name: "lloyds", domains: ["lloydsbank.com", "lloydsbank.co.uk", "lloydsbankinggroup.com"] },
  { name: "natwest", domains: ["natwest.com", "natwestgroup.com"] },
  { name: "santander", domains: ["santander.com", "santander.co.uk", "santander.com.br", "santanderbank.com", "santander.es", "santander.com.mx"] },
  { name: "revolut", domains: ["revolut.com", "revolut.me"] },
  { name: "monzo", domains: ["monzo.com", "monzo.me"] },
  { name: "wise", domains: ["wise.com", "transferwise.com"] },
  { name: "venmo", domains: ["venmo.com"] },
  { name: "cashapp", domains: ["cash.app", "squareup.com", "square.com", "block.xyz"] },
  { name: "zelle", domains: ["zellepay.com", "zelle.com"] },
  { name: "coinbase", domains: ["coinbase.com", "cb.com"] },
  { name: "binance", domains: ["binance.com", "binance.us", "bnbstatic.com"] },
  { name: "kraken", domains: ["kraken.com"] },
  { name: "metamask", domains: ["metamask.io"] },
  { name: "ledger", domains: ["ledger.com"] },
  { name: "trezor", domains: ["trezor.io"] },
  { name: "opensea", domains: ["opensea.io"] },
  { name: "uniswap", domains: ["uniswap.org", "app.uniswap.org"] },
  { name: "ebay", domains: ["ebay.com", "ebay.co.uk", "ebay.de", "ebay.ca", "ebay.com.au", "ebay.fr", "ebay.it", "ebay.es", "ebaystatic.com", "ebayimg.com"] },
  { name: "walmart", domains: ["walmart.com", "walmart.ca", "walmartimages.com"] },
  { name: "target", domains: ["target.com"] },
  { name: "bestbuy", domains: ["bestbuy.com", "bestbuy.ca"] },
  { name: "costco", domains: ["costco.com", "costco.ca"] },
  { name: "shopify", domains: ["shopify.com", "myshopify.com", "shopifycdn.com", "shop.app"] },
  { name: "etsy", domains: ["etsy.com", "etsystatic.com"] },
  { name: "aliexpress", domains: ["aliexpress.com", "aliexpress.us", "alicdn.com", "alibaba.com"] },
  { name: "dhl", domains: ["dhl.com", "dhl.de", "dhl.co.uk", "dhlparcel.nl", "dhlecommerce.com"] },
  { name: "fedex", domains: ["fedex.com"] },
  { name: "ups", domains: ["ups.com"] },
  { name: "usps", domains: ["usps.com", "usps.gov"] },
  { name: "royalmail", domains: ["royalmail.com", "royalmail.co.uk"] },
  { name: "dropbox", domains: ["dropbox.com", "dropboxusercontent.com", "db.tt"] },
  { name: "docusign", domains: ["docusign.com", "docusign.net"] },
  { name: "adobe", domains: ["adobe.com", "adobelogin.com", "acrobat.com", "adobe.io", "typekit.net"] },
  { name: "zoom", domains: ["zoom.us", "zoom.com", "zoomgov.com"] },
  { name: "slack", domains: ["slack.com", "slack-edge.com", "slackb.com"] },
  { name: "discord", domains: ["discord.com", "discord.gg", "discordapp.com", "discordapp.net", "discord.media"] },
  { name: "telegram", domains: ["telegram.org", "t.me", "telegram.me", "telesco.pe"] },
  { name: "steam", domains: ["steampowered.com", "steamcommunity.com", "steamstatic.com", "steamgames.com", "s.team", "valvesoftware.com"] },
  { name: "steamcommunity", domains: ["steamcommunity.com", "steampowered.com"] },
  { name: "epicgames", domains: ["epicgames.com", "unrealengine.com", "fortnite.com"] },
  { name: "roblox", domains: ["roblox.com", "rbxcdn.com"] },
  { name: "playstation", domains: ["playstation.com", "sonyentertainmentnetwork.com", "sony.com"] },
  { name: "nintendo", domains: ["nintendo.com", "nintendo.net", "nintendo.co.jp"] },
  { name: "spotify", domains: ["spotify.com", "scdn.co", "spotifycdn.com"] },
  { name: "github", domains: ["github.com", "github.io", "githubusercontent.com", "githubassets.com", "github.dev"] },
  { name: "yahoo", domains: ["yahoo.com", "yahoo.co.jp", "yimg.com", "aol.com", "yahoo.co.uk"] },
  { name: "protonmail", domains: ["proton.me", "protonmail.com", "protonmail.ch", "pm.me"] },
  { name: "twitch", domains: ["twitch.tv", "ttvnw.net", "jtvnw.net"] },
  { name: "tiktok", domains: ["tiktok.com", "tiktokcdn.com", "tiktokv.com", "bytedance.com"] },
  { name: "snapchat", domains: ["snapchat.com", "snap.com", "sc-cdn.net"] },
  { name: "reddit", domains: ["reddit.com", "redd.it", "redditstatic.com", "redditmedia.com"] },
  { name: "wordpress", domains: ["wordpress.com", "wordpress.org", "wp.com"] },
  { name: "godaddy", domains: ["godaddy.com", "secureserver.net"] },
  { name: "namecheap", domains: ["namecheap.com"] },
  { name: "cloudflare", domains: ["cloudflare.com", "cloudflare.net", "cloudflareinsights.com"] },
  { name: "irs", domains: ["irs.gov"] },
  { name: "hmrc", domains: ["hmrc.gov.uk", "gov.uk", "tax.service.gov.uk"] },
  { name: "intuit", domains: ["intuit.com", "turbotax.com", "quickbooks.com", "mint.com", "creditkarma.com"] },
  { name: "turbotax", domains: ["turbotax.com", "intuit.com"] },
  { name: "att", domains: ["att.com", "att.net"] },
  { name: "verizon", domains: ["verizon.com", "verizon.net", "verizonwireless.com", "vzw.com"] },
  { name: "tmobile", domains: ["t-mobile.com", "tmobile.com", "sprint.com"] },
  { name: "comcast", domains: ["comcast.com", "xfinity.com", "comcast.net"] },
  { name: "xfinity", domains: ["xfinity.com", "comcast.com", "comcast.net"] },
  { name: "uber", domains: ["uber.com", "ubereats.com"] },
  { name: "airbnb", domains: ["airbnb.com", "airbnb.co.uk", "airbnb.ca", "airbnb.de", "airbnb.fr", "muscache.com"] },
  { name: "booking", domains: ["booking.com", "bstatic.com"] },
  { name: "expedia", domains: ["expedia.com", "expedia.co.uk", "expedia.ca", "trvl-px.com", "expediagroup.com"] },
  { name: "doordash", domains: ["doordash.com"] },
  { name: "instacart", domains: ["instacart.com"] },
  { name: "okta", domains: ["okta.com", "oktacdn.com", "okta-emea.com", "oktapreview.com"] },
  { name: "onelogin", domains: ["onelogin.com"] },
  { name: "lastpass", domains: ["lastpass.com", "lastpass.eu"] },
  { name: "1password", domains: ["1password.com", "1password.ca", "1password.eu", "agilebits.com"] },
  { name: "bitwarden", domains: ["bitwarden.com", "bitwarden.eu"] },
  { name: "dashlane", domains: ["dashlane.com"] },
  { name: "norton", domains: ["norton.com", "nortonlifelock.com", "gendigital.com", "lifelock.com"] },
  { name: "mcafee", domains: ["mcafee.com"] },
  { name: "geeksquad", domains: ["bestbuy.com", "geeksquad.com"] },
  { name: "ticketmaster", domains: ["ticketmaster.com", "ticketmaster.co.uk", "livenation.com", "tmol.co"] },
  { name: "chatgpt", domains: ["chatgpt.com", "openai.com", "oaistatic.com", "oaiusercontent.com"] },
  { name: "openai", domains: ["openai.com", "chatgpt.com", "oaistatic.com"] },
  { name: "anthropic", domains: ["anthropic.com", "claude.ai", "claude.com"] },
  { name: "claude", domains: ["claude.ai", "claude.com", "anthropic.com"] },
];
})();
